[package]
name = "askama_derive"
version = "0.14.0"
description = "Code generator of Askama templating engine"
homepage = "https://github.com/askama-rs/askama"
repository = "https://github.com/askama-rs/askama"
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2024"
rust-version = "1.88"
publish = false

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--generate-link-to-definition", "--cfg=docsrs"]

[[bench]]
name = "derive-template"
harness = false

[dependencies]
parser = { package = "askama_parser", version = "=0.14.0", path = "../askama_parser" }

basic-toml = { version = "0.1.1", optional = true }
pulldown-cmark = { version = "0.13.0", optional = true, default-features = false }
serde = { version = "1.0", optional = true }
serde_derive = { version = "1.0", optional = true }

memchr = "2"
proc-macro2 = { version = "1", default-features = false }
quote = { version = "1", default-features = false }
rustc-hash = "2.0.0"
syn = { version = "2.0.3", default-features = false, features = ["clone-impls", "derive", "parsing", "printing"] }

[dev-dependencies]
console = "0.16.0"
criterion = "0.7"
prettyplease = "0.2.20"
similar = "2.6.0"
syn = { version = "2.0.3", features = ["full"] }

[features]
# Use every feature to aid testing. `askama_macros` will opt-out of default features.
default = [
    "alloc",
    "blocks",
    "code-in-doc",
    "config",
    "external-sources",
    "proc-macro",
    "serde_json",
    "std",
    "urlencode",
]

alloc = []
blocks = ["syn/full"]
code-in-doc = ["dep:pulldown-cmark"]
config = ["external-sources", "dep:basic-toml", "dep:serde", "dep:serde_derive", "parser/config"]
external-sources = []
proc-macro = ["proc-macro2/proc-macro"]
serde_json = []
std = ["alloc"]
urlencode = []
